openapi: "3.0.1"
info:
  title: "Rasa - Server Endpoints"
  version: "0.0.0"
  description: >-
    The Rasa server provides endpoints to retrieve trackers of
    conversations as well as endpoints to modify them. Additionally, 
    enpoints for training and evaluating models are provided.
servers:
  - url: "http://localhost:5005"
    description: "Local development server"
    
x-reuse:
  tracker:
    &tracker-example
    sender_id: default
    latest_event_time: 1537645578.314389
    latest_input_channel: rest
    paused: false
    slots: {}
    followup_action:
    latest_message:
      text: hello
      entities: []
      intent:
        confidence: 0.57
        name: greet
      intent_ranking:
      - confidence: 0.57
        name: greet
      - confidence: 0.33
        name: goodbye
    events:
    - event: action
      name: action_listen
      timestamp: 1537645578.274815
    - event: user
      input_channel: rest
      text: hello
      timestamp: 1537645578.314389
      parse_data:
        text: hello
        entities: []
        intent:
          confidence: 0.57
          name: greet
        intent_ranking:
        - confidence: 0.57
          name: greet
        - confidence: 0.33
          name: goodbye

paths:
  /:
    get:
      tags:
      - Meta Information
      summary: Health endpoint of Rasa Server
      description: >-
        This URL can be used as an endpoint to run
        health checks against. When the server is running
        this will return 200.
      responses:
        200:
          description: Up and running
          content:
            text/plain:
              schema:
                type: string
                description: Welcome text of Rasa Server
              example: >-
                Hello from Rasa: 0.12.0

  /version:
    get:
      tags:
      - Meta Information
      summary: Meta Info about Rasa Server
      description: >-
        Metadata about the running instance.
      responses:
        200:
          description: Version of Rasa
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    description: >-
                      Core version number
                  minimum_compatible_version:
                    type: string
                    description: >-
                      Minimum version this Rasa version is
                      able to load models from
              example:
                version: 0.12.0
                minimum_compatible_version: 0.12.0

  /status:
    get:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Meta Information
      summary: Status of the currently loaded agent and data router
      description: >-
        Information about the currently loaded agent and data router.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
              example:
                  core:
                    model_fingerprint: 4523wyfgr4q2
                    is_ready: true
                  nlu:
                    max_worker_processes: 5
                    current_worker_processes: 1
                    loaded_model: restaurant_bot
                  
                
  /conversations/{sender_id}/tracker:
    get:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Tracker
      summary: Retrieve a conversations tracker
      description: >-
        The tracker represents the state of the conversation.
        The state of the tracker is created by applying a
        sequence of events, which modify the state. These
        events can optionally be included in the response.
      parameters:
      - $ref: '#/components/parameters/senderId'
      - $ref: '#/components/parameters/includeEvents'
      responses:
        200:
          $ref: '#/components/responses/200Tracker'
        404:
          description: Invalid event verbosity format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                version: "0.12.0"
                status: "failure"
                message: >-
                  Invalid parameter value for 'include_events'.
                  Should be one of ALL, AFTER_RESTART, APPLIED, NONE
                reason: "InvalidParameter"
                code: 400
        403:
          $ref: '#/components/responses/403Permissions'
        503:
          $ref: '#/components/responses/503Tracker'

  /conversations/{sender_id}/story:
    get:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Tracker
      summary: Retrieve an end-to-end story corresponding to a conversation
      description: >-
        The story represents the whole conversation, in end-to-end
        format. This can be posted to the /evaluate endpoint and used
        as a test.
      parameters:
      - $ref: '#/components/parameters/senderId'
      responses:
        200:
          $ref: '#/components/responses/200Story'
        403:
          $ref: '#/components/responses/403Permissions'
        503:
          $ref: '#/components/responses/503Tracker'

  /conversations/{sender_id}/execute:
    post:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Tracker
      summary: Run an action in a conversation.
      description: >-
        Runs the action, calling the action server if necessary
        Any responses sent by the executed action will be returned as
        part of the endpoints result, they will not be sent over a
        connected output channel.
      parameters:
      - $ref: '#/components/parameters/senderId'
      - $ref: '#/components/parameters/includeEvents'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: >-
                    Name of the action to be executed
                  type: string
                policy:
                  description: >-
                    Name of the policy that predicted the action (optional).
                  type: string
                confidence:
                  description: >-
                    Confidence of the prediction (optional).
                  type: number
              required: ["name"]
            example:
              action: utter_greet
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  tracker:
                    $ref: '#/components/schemas/Tracker'
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/BotMessage'
        400:
          $ref: '#/components/responses/400InvalidRequest'
        403:
          $ref: '#/components/responses/403Permissions'
        500:
          $ref: '#/components/responses/500Action'

  /conversations/{sender_id}/predict:
    post:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Tracker
      summary: Predict the next action
      description: >-
        Runs the conversations tracker through the model's
        policies to predict the scores of all actions present
        in the model's domain. Actions are returned in the
        'scores' array, sorted on their 'score' values.
        The state of the tracker is not modified.
      parameters:
      - $ref: '#/components/parameters/senderId'
      - $ref: '#/components/parameters/includeEvents'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PredictResult'
              examples:
                PredictResult:
                  $ref: '#/components/examples/PredictResult'
        403:
          $ref: '#/components/responses/403Permissions'
        500:
          $ref: '#/components/responses/500Action'

  /conversations/{sender_id}/tracker/events:
    post:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Tracker
      summary: Append an event to a tracker
      description: >-
        Append a new event to the tracker state of the conversation.
        Any existing events will be kept and the new events will be
        appended, updating the existing state.
      parameters:
      - $ref: '#/components/parameters/senderId'
      - $ref: '#/components/parameters/includeEvents'
      requestBody:
        $ref: '#/components/requestBodies/Event'
      responses:
        200:
          $ref: '#/components/responses/200Tracker'
        403:
          $ref: '#/components/responses/403Permissions'

    put:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Tracker
      summary: Replace a trackers events
      description: >-
        Replace all of the events of a tracker with the passed
        list of events. This endpoint should not be used to
        modify trackers in a production setup, but rather
        for creating training data.
      parameters:
      - $ref: '#/components/parameters/senderId'
      - $ref: '#/components/parameters/includeEvents'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Event'
            examples:
              Events:
                $ref: '#/components/examples/Events'

      responses:
        200:
          $ref: '#/components/responses/200Tracker'
        400:
          $ref: '#/components/responses/400Events'
        403:
          $ref: '#/components/responses/403Permissions'

  /conversations/{sender_id}/messages:
    post:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Tracker
      summary: Add a message to a tracker
      description: >-
        Adds a message to a tracker. This doesn't trigger
        the prediction loop. It will log the message
        on the tracker and return, no actions will be
        predicted or run. This is often used together with the
        predict endpoint.
      parameters:
      - $ref: '#/components/parameters/senderId'
      - $ref: '#/components/parameters/includeEvents'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: >-
                    Message text
                sender:
                  type: string
                  description: >-
                    Origin of the message - who sent it
                  enum:
                    - user
                parse_data:
                  $ref: '#/components/schemas/ParseData'
              required: ["message", "sender"]
            example:
              sender: user
              message: hello
              parse_data:
                text: hello
                entities: []
                intent:
                  confidence: 0.57
                  name: greet
                intent_ranking:
                - confidence: 0.57
                  name: greet
                - confidence: 0.33
                  name: goodbye
      responses:
        200:
          $ref: '#/components/responses/200Tracker'
        403:
          $ref: '#/components/responses/403Permissions'
        500:
          description: Message Exception
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                version: "0.12.0"
                status: "failure"
                message: >-
                  An exception occurred while logging the message
                reason: "MessageException"
                code: 500

  /models/train:
    post:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Model
      summary: Train a Rasa Stack model
      description: >-
        Trains a Rasa Stack model. A stack model is a model combining a
        trained dialogue model with an NLU model.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StackTrainingRequest'
            examples:
              StackTrainingRequest:
                $ref: '#/components/examples/StackTrainingRequest'
      responses:
        200:
          description: Zipped Rasa Stack model
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/StackTrainingResult'
        400:
          $ref: '#/components/responses/400Training'
          
  /models/nlu/train:
    post:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Model
      summary: Train a Rasa NLU model
      description: >-
        Trains a Rasa NLU model.
      parameters:
      - $ref: '#/components/parameters/model_name'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StackTrainingRequest'
            examples:
              StackTrainingRequest:
                $ref: '#/components/examples/StackTrainingRequest'
      responses:
        200:
          description: Zipped Rasa Stack model
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/StackTrainingResult'
        400:
          $ref: '#/components/responses/400Training'

  /models/finetune:
    post:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Model
      summary: Fintune ML model
      description: >-
        Continue the ML training of a model on the provided events.
        **Fine tuning only works, if the model has been trained in
        memory before. It does not work if the model was persisted
        and loaded again.**
      parameters:
      - $ref: '#/components/parameters/epochs'
      - $ref: '#/components/parameters/batch_size'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Event'
            examples:
              Events:
                $ref: '#/components/examples/Events'
      responses:
        204:
          description: Model was successfully finetuned.
        400:
          $ref: '#/components/responses/400Events'
        500:
          $ref: '#/components/responses/500Action'

  /models/evaluate/stories:
    post:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Model
      summary: Evaluate stories
      description: >-
        Evaluates one or multiple stories against the currently loaded stack model.
      operationId: evaluateStories
      parameters:
      - $ref: '#/components/parameters/e2e'
      requestBody:
        required: true
        content:
          text/markdown:
            schema:
              type: string
            example: >-
              ## story_00055028
              * greet
               - utter_ask_howcanhelp
              * inform{"cuisine": "indian", "people": "two", "price": "moderate"}
               - utter_on_it
               - utter_ask_location
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvaluationResult'
              examples:
                PredictResult:
                  $ref: '#/components/examples/EvaluationResult'
        400:
          $ref: '#/components/responses/400Evaluation'

  /models/evaluate/intents:
    post:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Model
      summary: Perform an intent evaluation
      description: >-
        Evaluates NLU intents on a Rasa Stack model or Rasa NLU model.
      parameters:
      - $ref: '#/components/parameters/model_name'
      - $ref: '#/components/parameters/model_type'
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/IntentEvaluationRequest'
      responses:
        200:
          description: Intent evaluation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IntentEvaluationResult'
              examples:
                IntentEvaluation:
                  $ref: '#/components/examples/IntentEvaluationResult'
        400:
          $ref: '#/components/responses/400IntentEvaluation'

  /models/predict:
    post:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Model
      summary: Predict an action on a temporary state
      description: >-
        Predicts the next action on the tracker state as it is
        posted to this endpoint. Core will create a temporary
        tracker from the provided events and will use it to
        predict an action. No messages will be sent and no
        action will be run.
      parameters:
      - $ref: '#/components/parameters/includeEvents'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Event'
            example:
              - event: action
                name: action_listen
              - event: user
                parse_data:
                  entities: []
                  intent:
                    confidence: 0.57
                    name: greet
                  text: hello
                text: hello
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PredictResult'
              examples:
                PredictResult:
                  $ref: '#/components/examples/PredictResult'
        403:
          $ref: '#/components/responses/403Permissions'
        500:
          $ref: '#/components/responses/500Action'

  /models/parse:
    post:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Model
      summary: Parse a message using the loaded NLU model
      description: >-
        Predicts the intent and entities of the message
        posted to this endpoint. No messages will be stored
        to a conversation and no action will be run. This will
        just retrieve the NLU parse results.
      parameters:
      - $ref: '#/components/parameters/model_name'
      - $ref: '#/components/parameters/model_type'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: Message to be parsed
            example:
              text: "Hello, I am Rasa!"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParseData'
        404:
          $ref: '#/components/responses/404InvalidModel'
        403:
          $ref: '#/components/responses/403Permissions'
        500:
          $ref: '#/components/responses/500ServerError'
          
  /models:
    put:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Model
      summary: Replace a trained model
      description: >-
        Upload a trained model to the server. The server
        will unzip the uploaded file and try to load the model
        this will replace the previously loaded model.
      parameters:
      - $ref: '#/components/parameters/model_type'
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                model:
                  description: Zipped model file
                  type: string
                  format: binary
      responses:
        204:
          description: Success
        400:
          description: No Model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                version: "0.12.0"
                status: "failure"
                message: >-
                  No agent loaded.
                reason: "NoAgent"
                code: 400

    delete:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Model
      summary: Unload a trained model
      description: >-
        Unload a trained model from the server.
      parameters:
      - $ref: '#/components/parameters/model_name'
      responses:
        204:
          description: Success
        400:
          description: No Model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                version: "0.12.0"
                status: "failure"
                message: >-
                  No agent loaded.
                reason: "NoAgent"
                code: 400

  /domain:
    get:
      security:
      - TokenAuth: []
      - JWT: []
      tags:
      - Domain
      summary: Retrieve the loaded domain
      description: >-
        Return the domain specification the currently loaded model
        is using.
      operationId: getDomain
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
            application/yaml:
              schema:
                $ref: '#/components/schemas/Domain'
                
components:
  securitySchemes:
    TokenAuth:
      type: apiKey
      in: query
      name: token
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    model_type:
      in: query
      name: model_type
      description: Type of model
      schema:
        type: string
        default: NLU
        enum:
          - NLU
          - STACK
          - CORE
      required: false
    model_name:
      in: query
      name: model_name
      description: Name of the model
      schema:
        type: string
      required: false
    senderId:
      in: path
      name: sender_id
      example: default
      description: Id of the conversation
      schema:
        type: string
      required: true
    batch_size:
      in: query
      name: batch_size
      description: Batch size to use for training.
      schema:
        type: number
        default: 5
      required: false
    epochs:
      in: query
      name: epochs
      description: Number of epochs to train.
      schema:
        type: number
        default: 30
      required: false
    e2e:
      in: query
      name: e2e
      description: Perform an end-to-end evaluation on the posted stories
      schema:
        type: boolean
        default: false
      required: false
    includeEvents:
      in: query
      name: include_events
      description: >-
        Specify which events of the tracker the response
        should contain.
      schema:
        type: string
        default: AFTER_RESTART
        enum:
          - ALL
          - APPLIED
          - AFTER_RESTART
          - NONE

  requestBodies:
    Event:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Event'
          examples:
            action:
              $ref: '#/components/examples/ActionExecuted'
            agent:
              $ref: '#/components/examples/AgentUttered'
            bot:
              $ref: '#/components/examples/BotUttered'
            export:
              $ref: '#/components/examples/StoryExported'
            followup:
              $ref: '#/components/examples/FollowupAction'
            pause:
              $ref: '#/components/examples/ConversationPaused'
            reminder:
              $ref: '#/components/examples/ReminderScheduled'
            reset_slots:
              $ref: '#/components/examples/AllSlotsReset'
            restart:
              $ref: '#/components/examples/Restarted'
            resume:
              $ref: '#/components/examples/ConversationResumed'
            rewind:
              $ref: '#/components/examples/UserUtteranceReverted'
            slot:
              $ref: '#/components/examples/SlotSet'
            undo:
              $ref: '#/components/examples/ActionReverted'
            user:
              $ref: '#/components/examples/UserUttered'

  examples:
    Tracker:
      value:
        <<: *tracker-example

    Events:
      value:
      - event: action
        name: action_listen
      - event: user
        text: hello
        parse_data:
          entities: []
          intent:
            confidence: 0.57
            name: greet
          text: hello

    ActionExecuted:
      value:
        event: action
        name: utter_greet
    ActionReverted:
      value:
        event: undo
    AgentUttered:
      value:
        event: agent
        text: Hello
    AllSlotsReset:
      value:
        event: rewind
    BotUttered:
      value:
        event: bot
        text: Hello there
    ConversationPaused:
      value:
        event: pause
    ConversationResumed:
      value:
        event: resume
    FollowupAction:
      value:
        event: followup
        name: utter_greet
    ReminderScheduled:
      value:
        event: reminder
        action: utter_greet
        date_time: "2018-09-22T20:57:39.835946"
        name: my_reminder
        kill_on_user_msg: true
    Restarted:
      value:
        event: restart
    SlotSet:
      value:
        event: slot
        name: cuisine
        value: italian
    StoryExported:
      value:
        event: export
    UserUtteranceReverted:
      value:
        event: rewind
    UserUttered:
      value:
        event: user
        text: I like mexican food
        parse_data:
          text: I like mexican food
          intent:
            name: restaurant_search
            confidence: 0.85
          entities:
          - start: 7
            end: 14
            value: mexican
            entity: cuisine
    PredictResult:
      value:
        scores:
          - action: utter_greet
            score: 0.85
          - action: action_listen
            score: 0.15
        policy: "policy_2_KerasPolicy"
        tracker:
          <<: *tracker-example
    EvaluationResult:
      value:
        accuracy: 0.9
        f1: 0.9333333333333333
        in_training_data_fraction: 0.8571428571428571
        precision: 1.0
        is_end_to_end_evaluation: true
        actions:
          - action: utter_ask_howcanhelp
            confidence: 1.0
            policy: policy_0_MemoizationPolicy
            predicted: utter_ask_howcanhelp
          - action: action_listen
            confidence: 0.7885686478768559
            policy: policy_1_RestaurantPolicy
            predicted: utter_ask_numpeople
        report: >-
          # classification report
                                 precision    recall  f1-score   support
                  action_listen       1.00      1.00      1.00         3
                          greet       1.00      1.00      1.00         1
                         inform       1.00      1.00      1.00         2
           utter_ask_howcanhelp       1.00      1.00      1.00         1
             utter_ask_location       1.00      1.00      1.00         1
            utter_ask_numpeople       0.00      0.00      0.00         0
                    utter_on_it       1.00      0.50      0.67         2

                    avg / total       1.00      0.90      0.93        10
    IntentEvaluationResult:
          value:
            intent_evaluation:
              - accuracy: 0.19047619047619047
                f1_score: 0.06095238095238095
                precision: 0.036281179138321996
                predictions:
                  - intent: greet
                    predicted: greet
                    text: hey
                    confidence: 1.0
                  - confidence: 0.9667317867279053
                    intent: mood_unhappy
                    predicted: mood_unhappy
                    text: not very good
                report: >-
                  # intent evaluation report
                            precision    recall  f1-score   support

                  goodbye        1.00      1.00      1.00         4
                  greet          1.00      1.00      1.00         6
                  mood_affirm    1.00      1.00      1.00         5
                  mood_deny      1.00      1.00      1.00         6
                  mood_great     1.00      1.00      1.00         8
                  mood_unhappy   1.00      1.00      1.00        10

                  micro avg      1.00      1.00      1.00        39
                  macro avg      1.00      1.00      1.00        39
                  weighted avg   1.00      1.00      1.00        39
            entity_evaluation:
              CRFEntityExtractor:
                accuracy: 1.0
                f1_score: 1.0
                precision: 1.0
                report: >-
                  # entity evaluation report
                             precision     recall  f1-score   support

                  no_entity       1.00      1.00      1.00        70

                  micro avg       1.00      1.00      1.00        70
                  macro avg       1.00      1.00      1.00        70
                  weighted avg    1.00      1.00      1.00        70

    StackTrainingRequest:
      value:
        config: >-
          # Configuration for Rasa NLU.
          # https://rasa.com/docs/nlu/components/
          language: en
          pipeline: supervised_embeddings

          # Configuration for Rasa Core.
          # https://rasa.com/docs/core/policies
          policies:
            - name: MemoizationPolicy
            - name: KerasPolicy
        domain: >-
          intents:
            - greet
            - goodbye
            - mood_affirm
            - mood_deny
            - mood_great
            - mood_unhappy

          actions:
          - utter_greet
          - utter_cheer_up
          - utter_did_that_help
          - utter_happy
          - utter_goodbye

          templates:
            utter_greet:
            - text: "Hey! How are you?"

            utter_cheer_up:
            - text: "Here is something to cheer you up:"
              image: "https://i.imgur.com/nGF1K8f.jpg"

            utter_did_that_help:
            - text: "Did that help you?"

            utter_happy:
            - text: "Great carry on!"

            utter_goodbye:
            - text: "Bye"
        nlu: >-
          ## intent:greet
          - hey
          - hello

          ## intent:goodbye
          - cu
          - good by
        stories: >-
          ## happy path
          * greet
            - utter_greet
          * mood_great
            - utter_happy

          ## sad path 1
          * greet
            - utter_greet
          * mood_unhappy
        out: models
        force: false

  responses:
    200Tracker:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Tracker'
          examples:
            Tracker:
              $ref: '#/components/examples/Tracker'

    200Story:
      description: Success
      content:
        text/markdown:
          example: >-
            ## story_00055028

            * greet: hello
             - utter_ask_howcanhelp
            * inform: I'm looking for a [moderately priced](price:moderate) 
            [Indian](cuisine) restaurant for [two](people) people
             - utter_on_it
             - utter_ask_location

    500Action:
      description: Action Exception
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            version: "0.12.0"
            status: "failure"
            message: >-
              An exception occurred while running the action
            reason: "ActionException"
            code: 500

    400Events:
      description: Invalid Events
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            version: "0.12.0"
            status: "failure"
            message: >-
              Supplied events are not valid.
            reason: "InvalidParameter"
            code: 400

    400InvalidRequest:
      description: Invalid request format
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            version: "0.12.0"
            status: "failure"
            message: >-
              Invalid Request format.
            reason: "InvalidParameter"
            code: 400

    400Evaluation:
      description: Failed Evaluation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            version: "0.12.0"
            status: "failure"
            message: >-
              Evaluation could not be created.
            reason: "FailedEvaluation"
            code: 400

    400IntentEvaluation:
      description: Failed intent evaluation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            version: "0.12.0"
            status: "failure"
            message: >-
              Evaluation could not be created.
            reason: "FailedIntentEvaluation"
            code: 400

    400Training:
      description: Failed Training
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            version: "0.12.0"
            status: "failure"
            message: >-
              Rasa Stack model could not be trained.
            reason: "TrainingError"
            code: 400

    403Permissions:
      description: User has insufficient permission.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            version: "0.12.0"
            status: "failure"
            message: >-
              User has insufficient permission to access resource.
            code: 403
            
    404InvalidModel:
      description: Invalid model provided.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            version: "0.12.0"
            status: "InvalidModel"
            message: >-
              Provided model is invalid.
            code: 404

    500ServerError:
      description: Tracker store is unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            version: "0.12.0"
            status: "ServerError"
            message: >-
              An unexpected error occurred.
            code: 500
          
    503Tracker:
      description: Tracker store is unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            version: "0.12.0"
            status: "failure"
            message: >-
              No tracker store available.
            reason: "NoTrackerStore"
            code: 503

  schemas:
    Entity:
      type: object
      description: Entities within a message
      properties:
        start:
          type: integer
          description: Char offset of the start
        end:
          type: integer
          description: Char offset of the end
        value:
          type: string
          description: Found value for entity
        entity:
          type: string
          description: Type of the entity
        confidence:
          type: number
      required: ["start", "end", "value", "entity"]
    Intent:
      type: object
      description: Intent of the text
      properties:
        confidence:
          type: number
          description: Confidence of the intent
        name:
          type: string
          description: Intent name
      required: ["confidence", "name"]
    ParseData:
      type: object
      properties:
        entites:
          type: array
          description: Parsed entities
          items:
            $ref: '#/components/schemas/Entity'
        intent:
          $ref: '#/components/schemas/Intent'
        intent_ranking:
          type: array
          description: Scores of all intents
          items:
            $ref: '#/components/schemas/Intent'
        text:
          type: string
          description: Text of the message
      description: >-
        NLU parser information. If set, message
        will not be passed through NLU, but instead
        this parsing information will be used.
      required: ["text"]
    action:
      allOf:
      - $ref: '#/components/schemas/Event'
      - type: object
        properties:
          name:
            type: string
            description: Action name
          policy:
            type: string
            description: Policy that predicted the action
          confidence:
            type: number
            description: Confidence of the prediction
        required: ["event", "name"]
    agent:
      allOf:
      - $ref: '#/components/schemas/Event'
      - type: object
        properties:
          text:
            type: string
            description: Message
          data:
            type: object
            description: Additional data
        required: ["event", "text"]
    bot:
      allOf:
      - $ref: '#/components/schemas/Event'
      - type: object
        properties:
          data:
            type: object
            nullable: true
            description: Additional data
          text:
            type: string
            description: Message
        required: ["event", "text"]
    export:
      allOf:
      - $ref: '#/components/schemas/Event'
    followup:
      allOf:
      - $ref: '#/components/schemas/Event'
      - type: object
        properties:
          name:
            type: string
            description: Action to be triggered
        required: ["event", "name"]
    pause:
      allOf:
      - $ref: '#/components/schemas/Event'
    reminder:
      allOf:
      - $ref: '#/components/schemas/Event'
      - type: object
        properties:
          action:
            type: string
            description: Action to be triggered
          date_time:
            type: string
            description: Trigger date
          name:
            type: string
            description: Name of the reminder
          kill_on_user_msg:
            default: true
            type: boolean
            description: Cancel the reminder if there is a user message
        required: ["event", "action", "date_time"]
    reset_slots:
      allOf:
      - $ref: '#/components/schemas/Event'
    restart:
      allOf:
      - $ref: '#/components/schemas/Event'
    resume:
      allOf:
      - $ref: '#/components/schemas/Event'
    rewind:
      allOf:
      - $ref: '#/components/schemas/Event'
    slot:
      allOf:
      - $ref: '#/components/schemas/Event'
      - type: object
        properties:
          name:
            type: string
            description: Name of slot
          value:
            type: string
            description: Value of slot
    undo:
      allOf:
      - $ref: '#/components/schemas/Event'
    user:
      description: A message from a user
      allOf:
      - $ref: '#/components/schemas/Event'
      - type: object
        properties:
          parse_data:
            $ref: '#/components/schemas/ParseData'
          text:
            type: string
        required: ["event", "text"]
    form_validation:
      allOf:
        - $ref: '#/components/schemas/Event'
        - type: object
          properties:
            validate:
              type: string #TODO
    form:
      allOf:
        - $ref: '#/components/schemas/Event'
        - type: object
          properties:
            name:
              type: string
    action_execution_rejected:
      allOf:
        - $ref: '#/components/schemas/Event'
        - type: object
          properties:
            name:
              type: string
            policy:
              type: string #todo
              nullable: true
            confidence:
              type: number
              nullable: true
    Event:
      type: object
      properties:
        event:
          type: string
          description: Event name
        timestamp:
          type: integer
          description: Time of application
      required: ["event"]
      discriminator:
        propertyName: event
    Domain:
      type: object
      description: The bot's domain.
      properties:
        config:
          type: object
          description: Addional option
          properties:
            store_entities_as_slots:
              type: boolean
              description: Store all entites as slot when found
        intents:
          type: array
          description: All intent names and properties
          items:
            $ref: '#/components/schemas/IntentDescription'
        entities:
          type: array
          description: All entity names
          items:
            type: string
        slots:
          description: Slot names and configuration
          type: object
          additionalProperties:
            $ref: '#/components/schemas/SlotDescription'
        templates:
          description: Bot response templates
          type: object
          additionalProperties:
            $ref: '#/components/schemas/TemplateDescription'
        actions:
          description: Available action names
          type: array
          items:
            type: string
    BotMessage:
      type: object
      properties:
        recipient_id:
          type: string
          description: Id of the message receiver
        text:
          type: string
          description: Message
        image:
          type: string
          description: Image URL
        buttons:
          type: array
          description: Quick reply buttons
          items:
            type: object
            properties:
              title:
                type: string
                description: Button caption
              payload:
                type: string
                description: Payload to be sent if button is clicked
        attachement:
          type: array
          description: Additional information
          items:
            type: object
            properties:
              title:
                type: string
                description: Attachement caption
              payload:
                type: string
                description: Attachement payload
    Tracker:
      type: object
      description: Conversation tracker which stores the conversation state.
      properties:
        sender_id:
          type: string
          description: Id of the conversation
        slots:
          type: array
          description: Slot values
          items:
            $ref: '#/components/schemas/Slot'
        latest_message:
          $ref: '#/components/schemas/ParseData'
        latest_event_time:
          type: number
          description: Most recent event time
        followup_action:
          type: string
          description: Deterministic scheduled next action
        paused:
          type: boolean
          description: Bot is pasued
        events:
          type: array
          description: Event history
          items:
            $ref: '#/components/schemas/Event'
        latest_input_channel:
          type: string
          description: Communication channel
        latest_action_name:
          type: string
          description: Name of last bot action
        active_form:
          type: object
          description: Name of the active form
          properties:
            name:
              type: string
              description: Name of the acive form

    Error:
      type: object
      properties:
        version:
          type: string
          description: Core version
        status:
          type: string
          enum: ["failure"]
          description: Status of the requested action
        message:
          type: string
          description: Error message
        reason:
          type: string
          description: Error category
        details:
          type: object
          description: Additional error information
        help:
          type: string
          description: Optional URL to additonal material
        code:
          type: number
          description: HTTP status code

    PredictResult:
      type: object
      properties:
        scores:
          type: array
          description: Prediction results
          items:
            type: object
            properties:
              action:
                type: string
                description: Action name
              score:
                type: number
                description: Assigned score
        policy:
          type: string
          description: >-
            Policy which predicted the most likely action
        tracker:
          $ref: '#/components/schemas/Tracker'

    StackTrainingRequest:
      type: object
      properties:
        domain:
          type: string
          description: Rasa Core domain in plain text
        config:
          type: string
          description: Rasa Stack config in plain text
        nlu:
          type: string
          description: Rasa NLU training data in markdown format
        stories:
          type: string
          description: Rasa Core stories in markdown format
        out:
          type: string
          description: Output directory
        force:
          type: boolean
          description: >-
            Force a model training even if the data has not changed
      required: ["domain", "config", "nlu", "stories"]

    StackTrainingResult:
      type: string
      format: binary

    IntentEvaluationRequest:
      type: string
      format: binary

    IntentEvaluationResult:
      type: object
      properties:
        intent_evaluattion:
          type: object
          description: Rasa NLU intent evaluation
          properties:
            report:
              type: string
            accuracy:
              type: number
            f1_score:
              type: number
            precision:
              type: number
            predictions:
              type: array
              items:
                type: object
                properties:
                  intent:
                    type: string
                  predicted:
                    type: string
                  text:
                    type: string
                  confidence:
                    type: number
        entity_evaluation:
          type: object
          description: Rasa NLU entity evaluation
          properties:
            extractor_name:
              type: object
              description: Entity evaluation result for entity extractor
              properties:
                report:
                  type: string
                precision:
                  type: number
                f1_score:
                  type: number
                accuracy:
                  type: number

    EvaluationResult:
      type: object
      properties:
        actions:
          type: array
          items:
            type: object
            properties:
              action:
                type: string
                description: Name of the actual action
              predicted:
                type: string
                description: Name of the predicted action
              policy:
                type: string
                description: Machine-learning policy used in the prediction
              confidence:
                type: string
                description: Confidence score of the prediction
          description: >-
            Accuracy of the classification,
            http://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html
        is_end_to_end_evaluation:
          type: boolean
          description: True if evaluation is end-to-end, false otherwise
        precision:
          type: number
          description: >-
            Precision of the classification, see
            http://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html
        f1:
          type: number
          description: >-
            F1 score of the classification,
            http://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html
        accuracy:
          type: number
          description: >-
            Accuracy of the classification,
            http://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html
        in_training_data_fraction:
          type: number
          description: >-
            Fraction of stories that are present in the training data of the
            model loaded at evaluation time.
        report:
          type: string
          description: >-
            Sklearn classifcation report, see
            http://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html
    Slot:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/SlotValue'
      example:
        slot_name: slot_value
    SlotValue:
      oneOf:
        - type: string
        - type: array
          items:
            type: string
    SlotDescription:
      type: object
      properties:
        auto_fill:
          type: boolean
        initial_value:
          type: string
          nullable: true
        type:
          type: string
        values:
          type: array
          items:
            type: string
      required: ['type', 'auto_fill']
    TemplateDescription:
      type: object
      properties:
        text:
          type: string
          description: Template text
      required: ['text']
    IntentDescription:
      type: object
      additionalProperties:
        type: object
        properties:
          use_entities:
            type: boolean
